from pathlib import Path
base=Path(__file__).parent;s=base/'source/StreamMeCo'
p=s/'mmagent/utils/asr_resilience.py';t=p.read_text().replace("saved=json.loads(cache.read_text())","cache_started=time.perf_counter()\n        saved=json.loads(cache.read_text())").replace("latency_ms=0)","latency_ms=(time.perf_counter()-cache_started)*1000, measurement_kind='cache_read_not_provider_inference', cache_file=cache.name)");p.write_text(t)
p=s/'benchmarks/egolife_first10.py';t=p.read_text().replace('        if args.max_segments: plan=plan[:args.max_segments]',"        write_json({'segments':len(plan),'source_clips':len({str(r[0]) for r in plan}),'plan':[{'source':str(r[0]),'start':r[1],'end':r[2]} for r in plan]},args.results/'segment_plan.json')\n        if args.max_segments: plan=plan[:args.max_segments]");p.write_text(t)
t=Path('gpu_setup/egolife_gemini/environment.sh').read_text().replace('SMC=$ROOT/StreamMeCo','SMC=$ROOT/egolife_10q_qwen35_4b_fps2/code/StreamMeCo').replace('MANDOL=$ROOT/Mandol','MANDOL=$ROOT/egolife_10q_qwen35_4b_fps2/code/Mandol').replace('RUN=$ROOT/egolife_10q_gemini','RUN=$ROOT/egolife_10q_qwen35_4b_fps2').replace('export EGOLIFE_GEMINI_ONLY=1','unset EGOLIFE_GEMINI_ONLY\nexport EGOLIFE_QWEN_ONLY=1\nexport QWEN_VLM_FPS=2\nexport QWEN_RUN=$RUN\nexport QWEN_URL=http://127.0.0.1:8766/generate').replace('unset QWEN_MODEL_PATH','export QWEN_MODEL_PATH=/opt/streammeco/models/Qwen3.5-4B\nunset QWEN_MAX_NEW_TOKENS')
(base/'environment.sh').write_text(t)
t=Path('gpu_setup/egolife_gemini/preflight.sh').read_text().replace('egolife_10q_gemini','egolife_10q_qwen35_4b_fps2').replace('gemini_runtime','qwen_runtime').replace("'gemini'","'qwen'").replace('--backend gemini','--backend qwen').replace('gemini-3.8-flash','Qwen/Qwen3.5-4B').replace('GEMINI','QWEN')
t=t.replace("assert s['reasoning_model']=='Qwen/Qwen3.5-4B' and len(s['completed'])==3", "assert s['reasoning_model']=='Qwen/Qwen3.5-4B' and len(s['completed'])==3\nassert all(x.get('status')=='committed' for x in s['segment_map'].values())\nimport json\nfor i in range(1,4):\n a=json.loads((root/'results/clip_audits'/f'clip_{i}_audit.json').read_text())\nassert json.loads((root/'results/segment_plan.json').read_text())['segments']==144")
(base/'preflight.sh').write_text(t)
t=Path('gpu_setup/egolife_gemini/run_pipeline.sh').read_text().replace('egolife_10q_gemini','egolife_10q_qwen35_4b_fps2').replace('egolife_10q tmux','egolife_10q_qwen tmux').replace('= egolife_10q ]','= egolife_10q_qwen ]').replace('session=egolife_10q','session=egolife_10q_qwen').replace('--backend gemini','--backend qwen').replace('gemini-3.8-flash','Qwen/Qwen3.5-4B').replace('benchmarks/gemini_runtime.py','benchmarks/qwen_runtime.py').replace('benchmarks/gemini_report.py','benchmarks/qwen_report.py').replace('mmagent/memory_processing_gemini.py','mmagent/memory_processing_local_qwen.py')
t=t.replace('[ "$(cat "$RUN/retest_d_exit_status.txt")" = 0 ] || exit 24\n','')
(base/'run_pipeline.sh').write_text(t)
